main:
  - name: About
    url: /#about
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Publications
    url: /#publications
    weight: 30
  - name: Working Papers
    url: /#working-papers
    weight: 40
  - name: Grants
    url: /#grants
    weight: 50
  - name: Teaching
    url: /#teaching
    weight: 60
  - name: CV
    url: /uploads/resume.pdf
    weight: 70
